### ISSUE TITLE
Support for additional RTS commands

### ISSUE THREAD

**Issue by morilm** [aequitas/python-rflink#3]
Hi!!!!

First of all thanks for the tool... Really helpfull

Can I ask if it will be possible to add additional RTS commands from the CLI?  It will help to pair and debug..

Special Control Commands - Send:
10;REBOOT; => Reboot RFLink Gateway hardware
10;RTSCLEAN; => Clean Rolling code table stored in internal EEPROM
10;RTSRECCLEAN=9 => Clean Rolling code record number (value from 0 - 15)
10;RTSSHOW; => Show Rolling code table stored in internal EEPROM (includes RTS settings)
10;RTSINVERT; => Toggle RTS ON/OFF inversion
10;RTSLONGTX; => Toggle RTS long transmit ON/OFF
10;RTS;1b602b;0123;PAIR; => Pairing for RTS rolling code: RTS protocol, address, rolling code number, PAIR command
10;RTS;1b602b;0123;0;PAIR; => Extended Pairing for RTS rolling code: RTS protocol, address, rolling code number, eeprom record number, PAIR command

I have taken the information from the RFLINK page:   http://www.nemcon.nl/blog2/protref

Thanks
Miguel

**Comment by aequitas** [comment]
sorry for the late response, I somehow don't get notifications for the repo.

I think this might be doable combined with: https://github.com/aequitas/python-rflink/pull/6

Can you explain your use case so a solution can be better tailored?
