### ISSUE TITLE
rflinkproxy uses Python 3.5 features

### ISSUE THREAD

**Issue by scop** [aequitas/python-rflink#31]
README and setup.* say that the package is for Python >= 3.4, but `rflinkproxy/__main__.py` contains `async def connect(...)`, that syntax is for Python >= 3.5 only. Perhaps fix by dropping support for 3.4 :) ?

**Comment by aequitas** [comment]
Or revert to python3.4 compatible syntax :). I see that file is not covered by tests so it doesn't fail on the py34 suite, I'll see what I can do about it

https://travis-ci.org/aequitas/python-rflink/jobs/625138878

**Comment by aequitas** [comment]
Python 3.4 compat restored
