### ISSUE TITLE
Message not controlled (Internal Pullup on RF-in disabled)

### ISSUE THREAD

**Issue by javicalle** [aequitas/python-rflink#35]
On RFLink startup I get the following `warning` trace:

> [rflink.protocol] dropping invalid data: 20;00;Internal Pullup on RF-in disabled

After reviewing the code ([here](https://github.com/aequitas/python-rflink/blob/867426db40eb25e4a5ff5aa16329adf853ee62d6/rflink/protocol.py#L69) and [here](https://github.com/aequitas/python-rflink/blob/867426db40eb25e4a5ff5aa16329adf853ee62d6/rflink/parser.py#L248)), I expected this type of trace to be captured as a `PACKET_VERSION`, but for some reason that escapes me, it is not being captured and is shown as a warning.

Even if the package was accepted as a `PACKET_VERSION`, later in the `decode_packet` method I think it would generate an error.

I know it is an insignificant error (only once during startup) and probably not worth the effort, but would it be possible to process the message correctly?

**Comment by aequitas** [comment]
The message does not match the `PACKET_VERSION` as it contains no version info. I think this is a whole new packet type of its own. I added some parsing code for this type of package: https://github.com/aequitas/python-rflink/pull/36
