### ISSUE TITLE
"dropping invalid data" warning

### ISSUE THREAD

**Issue by akasma74** [aequitas/python-rflink#40]
Occasionally I can see the following warning in my HA log

> 2020-02-15 08:48:48 WARNING (MainThread) [rflink.protocol] dropping invalid data: 20;82;Slave;Debug=f3 03 ac bf 83 -13325;

It does not seem to affect my setup but it would be great _not_ to have unnecessary warnings if at all possible.

**Comment by aequitas** [comment]
You can change the log level in home assistant to only error, just change debug in this example to error: https://www.home-assistant.io/integrations/rflink/#debug-logging

**Comment by akasma74** [comment]
Wow, that was quick.
I know I can change the log level. The question is if `warning` is the right level for that particular type of messages? Maybe it should be lower (say, `info`)?

**Comment by aequitas** [comment]
I agree, but currently I don't have a inclination to change it.
