### ISSUE TITLE
RFLINK  invalid data

### ISSUE THREAD

**Issue by FrColin** [aequitas/python-rflink#41]
Hello,
I am using RFLINK in the latest version RFLink firmware R48 with home assistant
I got many message in hass log:
[rflink.protocol] dropping invalid data: 20;84;Debug;RTS P1;a63f33003cf000665a5a;

the packet is not handled by the parser since the "Debug" word use lower case
and the regular expression in the valid_packet function didn't mach these 

my be we can add this to parser.y

>  **#** 20;84;Debug;RTS P1;a63f33003cf000665a5a;
> PACKET_DEBUGRTS = DELIM.join(["20", SEQUENCE, "Debug", DATA])

**Comment by FrColin** [comment]
since there is a space  in the message we need also need to change the DATA regexp to

> DEBUG_DATA_RTS = "[a-zA-Z0-9;=_ ]+"

so the correct re is 

> PACKET_DEBUGRTS = DELIM.join(["20", SEQUENCE, "Debug", DEBUG_DATA_RTS])

**Comment by aequitas** [comment]
Sound good, can you make a PR for this?

**Comment by FrColin** [comment]
Ok PR done
