### ISSUE TITLE
protocol with dash (-) issue

### ISSUE THREAD

**Issue by aschor** [aequitas/python-rflink#62]
Hi, I happen to have rf remotes, that use CAME-TOP432 protocol in rflink.

But I have an issue with this interacting from homeassistant :

my config :
```
switch:
  - platform: rflink
    devices:
      came-top432_0afa_01:
        name: switch came avec tiret
      cametop432_0afa_01:
        name: switch came SANS tiret
```

when I CLICK on the remote button, here is what is displayed on the serial of the rflink(32) :

`20;07;CAME-TOP432;ID=0xxx;SWITCH=01;CMD=ON;`

Notice the dash in the protocol name "CAME-TOP432".

but then, if I put homeassistant in debug, here are the relevant logs :

```
2021-12-31 10:45:18 DEBUG (MainThread) [rflink.protocol] received data: 20;07;CAME-TOP432;ID=0xxx;SWITCH=01;CMD=ON;
2021-12-31 10:45:18 DEBUG (MainThread) [rflink.protocol] got packet: 20;07;CAME-TOP432;ID=0xxx;SWITCH=01;CMD=ON;
2021-12-31 10:45:18 DEBUG (MainThread) [rflink.protocol] decoded packet: {'node': 'gateway', 'protocol': 'came-top432', 'id': '0xxx', 'switch': '01', 'command': 'on'}
2021-12-31 10:45:18 DEBUG (MainThread) [rflink.protocol] got event: {'id': 'cametop432_0xxx_01', 'command': 'on'}
```

there, the dash is stripped from the protocol in the event.

But then, from home assistant :
- playing with the "cametop432_0afa_01" switch .... triggers errors on rflink 
```
Message arrived [Ser2Net]:10;cametop432;0afa;01;on;
20;06;CMD UNKNOWN;
```

- playing with the "came-top432_0afa_01" switch triggers the switch correctly on the rflink gateway ....

- YET, playing with the remote ..... changes the state of the non-working "cametop432_0afa_01" switch in home assistant.... 
- and THEN this switch does work on the rflink gateway with no "cmd unknown". yeeeek ?

**Comment by aequitas** [comment]
should be solved by the PR you created, it will be automatically merged now when the tests pass. After that a new version will be build: https://github.com/aequitas/python-rflink/releases If you could take care of updating the package version in home assistant when the new version is out: https://github.com/home-assistant/core/blob/dev/homeassistant/components/rflink/manifest.json#L5
